---
title: "3d_plot"
output: 
  html_document:
   keep_md: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(plotly)
library(lattice)
#remotes::install_github("tylermorganwall/rayshader")
library(rayshader)
library(dlnm)
library(survival)
library(splines)
library(broom)
library(weathermetrics)
library(viridis)
library(reshape2)
library(magick)
library(av)
library(ggrepel)
library(cowplot)
library(gridGraphics)

```



## Input data

```{r}

cc_exposure_df <-
  read_rds(file = "data/cc_exposure_df.rds") 

cc_exposure_df <-
  cc_exposure_df %>% 
    mutate("wbgt_mean" = weathermetrics::celsius.to.fahrenheit(wbgt_mean),
           "wbgt_max" = weathermetrics::celsius.to.fahrenheit(wbgt_max))

base_service_df <-
   read_rds(file = "data/base_service_df.rds") 

# Add installation branch of service and climate region

cc_exposure_df <-
  cc_exposure_df %>% 
    left_join(base_service_df %>%
                rename(base_service = service) %>% 
                dplyr::select(installation_name, base_service, region), by = "installation_name") 



daily_indices <- 
  read_rds(file = "data/daily_indices.rds") %>% 
    filter(!installation %in% c("fort_drum", "fort_huachuca", "fort_lewis",
                                "lackland_afb", "fort_carson", "west_point_mil_reservation")) %>% 
    mutate("wbgt_mean" = weathermetrics::celsius.to.fahrenheit(wbgt_mean),
           "wbgt_max" = weathermetrics::celsius.to.fahrenheit(wbgt_max),
            installation = recode(installation,
              "mcb_camp_lejeune" = "camp_lejeune",
              "mcb_camp_pendleton" = "camp_pendleton",
              "fort_benning_ga" = "fort_benning",
              "fort_sam_houston" = "jbsa",
              "mcrd_beaufort_parris_island" = "parris_island",
              "mcb_quantico" = "quantico",
              "twentynine_palms_main_base" = "twentynine_palms")) 
     
```



## Inputs

```{r}

selected_index <- "tmp_f_mean"

# crossbasis options
set_lag <- 5    # total number days lag to assess
set_dr_df <- 5   # natural spline degrees of freedom for functional form of the dose-response curve
set_lag_df <- 4   # natural spline degrees of freedom for functional form of the lag

# crosspred options

set_increment <- 1   # crosspred "by = "
set_centered <- 60 # crosspred "cen= ", centered value for odds ratios 
set_min_temp <- set_centered   # crosspred lower bound


# set max plot index value (approximate, or rounded-down from max value in dataset)
set_max_plot_value <- case_when(
  selected_index %in% "wbgt_mean" ~ 86,
  selected_index %in% "wbgt_max" ~ 104,
  selected_index %in% "heat_index_mean" ~ 104,
  selected_index %in% "heat_index_max" ~ 116,
  selected_index %in% "tmp_f_mean" ~ 98,
  selected_index %in% "tmp_f_max" ~ 112,
    )

set_max_plot_value



# crosspred upper-bound
set_max_temp <- set_max_plot_value

set_max_temp


print_index <- case_when(
  selected_index %in% "wbgt_mean" ~ "Mean WBGT (°F)",
  selected_index %in% "wbgt_max" ~ "Max WBGT (°F)",
  selected_index %in% "heat_index_mean" ~ "Mean Heat Index (°F)",
  selected_index %in% "heat_index_max" ~ "Max Heat Index (°F)",
  selected_index %in% "tmp_f_mean" ~ "Mean Temperature (°F)",
  selected_index %in% "tmp_f_max" ~ "Max Temperature (°F)",
    )


print_index



```


## Lag function
```{r}

# DLNM
## Lags function

lags <- seq(set_lag) # Number of lags

lag_names <- paste("lag", formatC(lags, width = nchar(max(lags)), flag = "0"), 
  sep = "_")

lag_fun <- setNames(paste("dplyr::lag(., ", lags, ")"), lag_names)

```


## Create lag matrix for selected index; join to case-crossover dataframe

```{r, warning = FALSE}
 # create lag matrix

lag_matrix <-
  daily_indices %>% 
    filter(date %in% as.Date("1997-12-15"):as.Date("2019-12-31")) %>% 
      dplyr::select(installation, date, selected_index) %>% 
   group_by(installation) %>% 
   mutate_at(vars(selected_index), funs_(lag_fun)
  )


# join lag matrix to case-crossover dataframe

cc_lag_matrix <-
  cc_exposure_df %>% 
    filter(year %in% 1998:2019) %>% 
    dplyr::select(!selected_index) %>%    # remove to avoid double listing after join
    left_join(lag_matrix,  by = c("installation_name" = "installation", "date" = "date")) 


cc_lag_only <- 
  cc_lag_matrix %>% 
  dplyr::select(selected_index, lag_1:paste0("lag_", set_lag))
```


Restrict the DLNM to the range of values to be plotted (eg 60-86)


## Define DLNM cross-basis

```{r, warning = FALSE}

 
# Define dlnm cross-basis (penalized splines)

index_cb <-
    crossbasis(
      cc_lag_only,    
      lag = set_lag,    # of lags
      argvar = list(fun = "ns", df = set_dr_df),    #  functional form of the dose-response curve
      arglag = list(fun = "ns", df = set_lag_df))    #  functional form of the lags

summary(index_cb)

# run model and get prediction for selected_index


index_dlnm <- survival::clogit(case ~ 
                  index_cb +  # lagged, nonlinear term for exposure
                  strata(stratum), 
                  method = "efron",
                  data =  cc_exposure_df) 


pred_dlnm <- crosspred(index_cb, index_dlnm, by = set_increment, from = set_min_temp, to = set_max_temp, cen = set_centered, cumul = TRUE)


summary(pred_dlnm)

```


## 3D plot
(`dlnm` base plot)

```{r}

#3D Plot 

assign(paste0("plot_", selected_index, "_3d"),
  plot(pred_dlnm, ptype = "3d", 
     xlab = paste(print_index), zlab = "\nOR", ylab = "\nLag Day", 
     theta = 40, phi = 30, lphi = 30)
  )



#eval(parse(text = paste0("plot_", selected_index, "_3d")))

#write_rds(eval(parse(text = paste0("plot_", selected_index, "_3d"))), 
#  file = paste0("output/", paste0("plot_", selected_index, "_3d"), ".rds"))


A <-
  recordPlot(
 plot(pred_dlnm, ptype = "3d", 
     xlab = paste(print_index), zlab = "\nOR", ylab = "\nLag Day", 
     theta = 40, phi = 30, lphi = 30)
)

replayPlot(A)



```




## 3-d plots combined

```{r}

selected_index <- c("tmp_f_mean", "heat_index_mean","wbgt_mean","tmp_f_max", "heat_index_max", "wbgt_max")

patchwork_3d_df_5_4 <-
      (read_rds(paste0("output/plot_", selected_index[1], "_3d.rds")) |   
         read_rds(paste0("output/plot_", selected_index[2], "_3d.rds")) |  
         read_rds(paste0("output/plot_", selected_index[3], "_3d.rds"))   
         ) /
        (read_rds(paste0("output/plot_", selected_index[4], "_3d.rds")) |   
         read_rds(paste0("output/plot_", selected_index[5], "_3d.rds")) |  
         read_rds(paste0("output/plot_", selected_index[6], "_3d.rds"))) +
            plot_annotation(tag_levels = 'A') +
            plot_layout(guides = 'collect') & 
            theme(legend.position = "bottom")
  

```






## 3D model (rayshader)

```{r, eval = FALSE}

# https://rdrr.io/cran/dlnm/src/R/seqlag.R
seqlag <- function(lag, by = set_increment) seq(from = lag[1],to = lag[2], by = by)



to_plot <- 
  data.frame(index = pred_dlnm$predvar, 
             mean = pred_dlnm$allRRfit,
             lower = pred_dlnm$allRRlow,
             upper = pred_dlnm$allRRhigh)


to_3d <- list(x = matrix(pred_dlnm$predvar), 
              y = matrix(seqlag(pred_dlnm$lag, pred_dlnm$bylag)), 
              z = matrix(unlist(pred_dlnm$matfit), ncol = set_lag + 1, byrow = TRUE))


x <- as_vector(pred_dlnm$predvar)
y <- as.vector(seqlag(pred_dlnm$lag, pred_dlnm$bylag))
z <- pred_dlnm$matRRfit

df_3d <-  
  z %>% 
    melt() %>% 
    as_tibble() %>% 
    rename(
      selected_index = Var1,
      "Lag" = Var2,
      "OR" = value
    ) %>% 
    mutate(Lag = as.numeric(str_remove(Lag, "lag"))) 

df_3d$OR %>% summary()



# 3d plot with rayshader

gg_3d <-
  df_3d %>% 
  ggplot() +
    geom_raster(aes(x = selected_index, y = `Lag`, fill = `OR`)) +
    scale_fill_viridis()



plot_gg(gg_3d, multicore = TRUE, width = 5, height = 5, scale = 250)


# Render 3D movie

# filename_movie <- "output/mean_wbgt_3d.mp4"
# 
# render_movie(filename = filename_movie, type = "orbit", 
#              frames = 360,  phi = 30, zoom = 0.8, theta = -90,
#              title_text = "Mean WBGT Odds Ratio")


# 3D print file
#filename_stl = "output/mean_wbgt_3d.stl"
#save_3dprint(filename_stl, rotate = TRUE)
```




