---
title: "dlnm_fun"
author: "SL"
date: "10/19/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(survival)
library(splines)
library(broom)
library(dlnm)
library(plotly)
library(weathermetrics)
library(viridis)

```

## Load daily NLDAS indices and anomalies

```{r}

daily_indices <- read_rds(file = "D:/data/daily_indices.rds") %>% 
  rename(date = `lubridate::date(local_dttm)`) %>% 
  mutate(wbgt_f_mean = weathermetrics::celsius.to.fahrenheit(wbgt_u_mean),
         installation = recode(installation, 
                `pensacola_nas` = "pensacola",
                `portsmouth_nmc` = "portsmouth"))

daily_indices <-
  daily_indices %>% 
       mutate(installation = recode(installation, 
                  `pensacola_nas` = "pensacola",
                  `portsmouth_nmc` = "portsmouth"))



daily_indices %>% 
    filter(installation %in% "pensacola")


case_control_df <-
  read_rds("data/case_control_df.rds")


cc_exposure_df <-
  read_rds(file = "D:/data/cc_exposure_df.rds") %>% 
  mutate(wbgt_f_mean = weathermetrics::celsius.to.fahrenheit(wbgt_u_mean))


daily_indices %>% 
  count(installation) %>% View() #30 installation


case_control_df %>% 
  count(installation_name) %>% View() #24 installations

cc_exposure_df %>% 
  count(installation_name) %>% View() #24 installations

# DLNM
## Lags function

lags <- seq(7) # Number of lags

lag_names <- paste("lag", formatC(lags, width = nchar(max(lags)), flag = "0"), 
  sep = "_")

lag_fun <- setNames(paste("dplyr::lag(., ", lags, ")"), lag_names)

```


```{r}
## Cross-basis


selected_index <- "wbgt_f_mean"

dlnm_fun("wbgt_f_mean")


dlnm_fun = function(selected_index) {

  # inspect histogram
  
cc_exposure_df %>%
    filter(case %in% 1) %>% 
    ggplot(aes(x = wbgt_f_mean)) +
      geom_histogram(binwidth = 1) +
      theme_bw()
    
cc_exposure_df %>% summary()
  
  
  
  # create lag matrix

lag_matrix <-
   daily_indices %>% 
    filter(date %in% as.Date("1997-12-15"):as.Date("2019-12-31")) %>% 
      dplyr::select(installation, date, selected_index) %>% 
   group_by(installation) %>% 
   mutate_at(vars(selected_index), funs_(lag_fun)
  )



# join lag matrix to case-crossover dataframe

cc_lag_matrix <-
  cc_exposure_df %>% 
    filter(year %in% 1998:2019) %>% 
    dplyr::select(!selected_index) %>%    # remove to avoid double listing after join
    left_join(lag_matrix,  by = c("installation_name" = "installation", "date" = "date")) 


cc_lag_only <- 
  cc_lag_matrix %>% 
  dplyr::select(selected_index, lag_1:lag_7)


# Define dlnm cross-basis (penalized splines)

index_cb <-
    crossbasis(
      cc_lag_only,    
      lag = 7,    # of lags
      argvar = list(fun = "ns", df = 5),    #  functional form of the dose-response curve
      arglag = list(fun = "ns", df = 4))    #  functional form of the lags

summary(index_cb)

# run model and get prediction for selected_index


index_dlnm <- survival::clogit(case ~ 
                  index_cb +  # lagged, nonlinear term for exposure
                  strata(stratum), 
                  method = "efron",
                  data =  cc_exposure_df) 


pred_dlnm <- crosspred(index_cb, index_dlnm, by = 1, from = 0, to = 90, cumul = TRUE)

summary(pred_dlnm)

## Overall effect RRs

pred_dlnm$allRRfit[c("74", "78", "80", "82", "84", "86", "88")]

bind_cols(names(pred_dlnm$allRRfit), pred_dlnm$allRRfit, pred_dlnm$allRRlow, pred_dlnm$allRRhigh) %>% 
  dplyr::rename(var = 1, rr = 2, ci_low = 3, ci_high = 4) %>% 
  dplyr::filter(var %in% c("78", "82", "85", "88", "90"))




# Plot cross-predictions

# 3d Plot 

plot(pred_dlnm, 
     xlab = paste(selected_index), zlab = "\nRR", ylab = "\nLag", 
     theta = 40, phi = 30, lphi = 30,
     main = "1998-2019")


# Contour plot

plot(pred_dlnm, "contour",
     plot.title = title(xlab = selected_index, ylab = "Lag",
     main = "Contour graph \n1998-2019"), key.title = title("RR"))




# Slice Plot
# visualize association at specific lags 


# Overall effect

plot(pred_dlnm, "overall",
     lwd = 4,
     col = "darkred",
     main = "Overall effect \n  1998-2019", 
     xlab = paste(selected_index), 
     ylab = "HSI Rate Ratio")




# Plot dose-response curve at Lag 0

plot(pred_dlnm, "slices",
     var = 88,
     type = "p",
     ci = "bars",
     main = "Lag specific effects at 88 deg \n  1998-2019", 
     xlab = paste(selected_index), 
     ylab = "HSI Rate Ratio")




plot(pred_dlnm, "slices",
     lag = 0,
     #ylim = c(0, 10),
     lwd = 4,
     col = "darkred",
     main = "Exposure-Response at Lag 0 \n  1998-2019", 
     xlab = paste(selected_index), 
     ylab = "HSI Rate Ratio")


plot(pred_dlnm, "slices",
     lag = 1,
     lwd = 4,
     col = "darkred",
     main = "Exposure-Response at Lag 1 \n  1998-2019", 
     xlab = paste(selected_index), 
     ylab = "HSI Rate Ratio")

plot(pred_dlnm, "slices",
     lag = 2,
     lwd = 4,
     col = "darkred",
     main = "Exposure-Response at Lag 2 \n  1998-2019", 
     xlab = paste(selected_index), 
     ylab = "HSI Rate Ratio")


plot(pred_dlnm, "slices",
     lag = 3,
     lwd = 4,
     col = "darkred",
     main = "Exposure-Response at Lag 3 \n  1998-2019", 
     xlab = paste(selected_index), 
     ylab = "HSI Rate Ratio")


}


```



ggplot figures
```{r}

lag_matrix

cc_lag_matrix %>% 
  count(installation_name) %>% View()

cc_lag_only

index_cb

index_dlnm <- survival::clogit(case ~ 
                  index_cb +  # lagged, nonlinear term for exposure
                  strata(stratum), 
                  method = "efron",
                  data =  cc_exposure_df) 


pred_dlnm <- crosspred(index_cb, index_dlnm, by = 1, from = 0, to = 90, cumul = TRUE)


plot(pred_dlnm, "overall",
     lwd = 4,
     col = "darkred",
     main = "Overall effect \n  1998-2019", 
     xlab = paste(selected_index), 
     ylab = "HSI Rate Ratio")



# As ggplot
  # https://www.rdocumentation.org/packages/season/versions/0.3.8/vignettes/season-vignette.Rmd link assisted with example "Plot of the temperature and death association averaging over all lags"

 
to_plot <- 
  data.frame(index = pred_dlnm$predvar, 
             mean = pred_dlnm$allRRfit,
             lower = pred_dlnm$allRRlow,
             upper = pred_dlnm$allRRhigh)
  



ggplot(data = to_plot, aes(x = index, y = mean, ymin = lower, ymax = upper)) +
  geom_hline(lty = 2, yintercept = 1) + # horizontal reference line at no change in odds
  geom_ribbon(alpha = 0.2) +
  geom_line(size = 1.25) +
  xlab('WBGT (degrees F)') +
  ylab('Odds Ratio') +
  xlim(50, NA) +
  theme_bw() +
  ggtitle("Daily mean WBGT and HSI association averaged over all lags") +
  labs(caption = "Centered at 50°F") +
  theme(plot.caption = element_text(hjust = 0)) 
  

```


## Groups

### By installation

```{r density_plots}

summary(cc_lag_matrix) 

# Density plots
## Cases and Controls
cc_lag_matrix %>% 
  ggplot(aes(x = wbgt_f_mean)) +
  geom_density(fill = "purple4", alpha = 0.5) + 
      geom_rug(sides = "b") +
      theme_bw() +
      ggtitle("Density plot of mean daily WBGT from 1998-2019\n Case- and control-days") 

cc_lag_matrix %>% 
  count(installation_name)

summary(cc_lag_matrix)



cc_lag_matrix %>% 
  ggplot(aes(x = wbgt_f_mean, fill = installation_name)) +
  geom_density(alpha = .5) + 
  #facet_grid(~name) + 
  viridis::scale_fill_viridis(discrete = TRUE) +
      theme_bw() +
      ggtitle("Density plot of mean daily WBGT from 1998-2019") 


## Daily temperature indices - all days (filter 1998-2019)

daily_indices %>%
  filter(lubridate::year(date) >= 1998) %>% 
  ggplot(aes(x = wbgt_f_mean)) +
  geom_density(fill = "purple4", alpha = 0.5) + 
      geom_rug(sides = "b") +
      theme_bw() +
      ggtitle("Density plot of mean daily WBGT from 1998-2019\n All days") 
  


## Plot case days and all days together

cc_lag_matrix %>% 
  filter(case == 1) %>% 
  select(installation_name, d_event, wbgt_f_mean) %>%
  mutate(date_type = "case day") %>% 
  bind_rows(
    daily_indices %>%
      filter(lubridate::year(date) >= 1998) %>%
        select(installation, date, wbgt_f_mean) %>% 
        rename(installation_name = installation,
             d_event = date) %>% 
      mutate(date_type = "calendar day")
  ) %>% 
  ggplot(aes(x = wbgt_f_mean, fill = date_type)) +
  geom_density(alpha = 0.5) + 
      geom_rug(sides = "b") +
      theme_bw() +
      ggtitle("Density plot of mean daily WBGT from 1998-2019") 
    
 
# case vs. control   
cc_lag_matrix %>% 
  select(installation_name, d_event, wbgt_f_mean, case) %>%
  mutate(case = as_factor(case)) %>% 
  ggplot(aes(x = wbgt_f_mean, fill = case)) +
  geom_density(alpha = 0.5) + 
      geom_rug(sides = "b") +
      theme_bw() +
      ggtitle("Density plot of mean daily WBGT from 1998-2019") 
  


```


## Group Nest
```{r group_nest}


cc_lag_nest <-
  cc_lag_matrix %>% 
    select(-bmi, -control_date) %>%
    drop_na(selected_index) %>% 
    nest(., data = studyid:lag_7) 

cc_lag_nest$data[1] 

dlnm_map_fun = function(df) {

  cc_lag_only <- 
    df %>% 
    dplyr::select(selected_index, lag_1:lag_7)
      
  index_cb <-
      crossbasis(
        cc_lag_only,    
        lag = 7,    # of lags
        argvar = list(fun = "ns", df = 5),    #  functional form of the dose-response curve
        arglag = list(fun = "ns", df = 4))    #  functional form of the lags
   
  index_dlnm <- survival::clogit(case ~ 
                    index_cb +  # lagged, nonlinear term for exposure
                    strata(stratum), 
                    method = "efron",
                    data =  df) 
  
  
  return(crosspred(index_cb, index_dlnm, 
                   by = 1, from = 0, to = 90, cen = 50, cumul = TRUE)
  )

}


  
base_dlnm_nest <-  
  cc_lag_nest %>%
    mutate(pred_dlnm = 
             map(cc_lag_nest$data, dlnm_map_fun)
           )

base_dlnm_nest      


# Add column for ggplot

base_dlnm_nest <-
  base_dlnm_nest %>% 
    mutate(to_plot =
            map(.x = pred_dlnm, 
                .f = ~data.frame(index = .$predvar, 
              mean = .$allRRfit,
              lower = .$allRRlow,
              upper = .$allRRhigh))
)


base_dlnm_nest
base_dlnm_nest$to_plot[[1]]


base_dlnm_nest %>% 
  unnest(to_plot) %>% 
    ggplot(data = ., aes(x = index, y = mean, 
                         ymin = lower, ymax = upper,
                         color = installation_name, linetype = installation_name)) +
      geom_hline(lty = 2, yintercept = 1) + # horizontal reference line at no change in odds
      geom_ribbon(alpha = 0.05) +
      geom_line(size = 0.8) +
      xlab('WBGT (degrees F)') +
      ylab('Odds Ratio') +
      xlim(70, NA) +
      theme_bw() +
      ggtitle("Daily mean WBGT and HSI association averaged over all lags") +
      labs(caption = "Centered at 50°F") +
      theme(plot.caption = element_text(hjust = 0))

base_dlnm_nest %>% 
  unnest(to_plot) %>%
    ggplot(data = ., aes(x = index, y = mean, 
                         ymin = lower, ymax = upper,
                         color = installation_name, linetype = installation_name)) +
      geom_hline(lty = 2, yintercept = 1) + # horizontal reference line at no change in odds
      geom_line(size = 0.8) +
      xlab('WBGT (degrees F)') +
      ylab('Odds Ratio') +
      xlim(50, NA) +
      ylim(0, 100) +
      theme_bw() +
      ggtitle("Daily mean WBGT and HSI association averaged over all lags") +
      labs(caption = "Centered at 50°F") +
      theme(plot.caption = element_text(hjust = 0)) 

      #scale_color_viridis(discrete = TRUE, option = "magma")
```

