---
title: "dlnm"
author: "SL"
date: "10/19/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(survival)
library(splines)
library(broom)
library(dlnm)
library(plotly)


```

## Load daily NLDAS indices and anomalies

```{r}

daily_indices <- read_rds(file = "D:/data/daily_indices.rds") %>% 
  rename(date = `lubridate::date(local_dttm)`)

daily_anomalies <- read_rds(file = "D:/data/daily_anomalies.rds")

daily_nldas <-
  daily_indices %>% 
    left_join(dplyr::select(daily_anomalies, installation, date, tmp_mean_anom, hi_mean_anom, wbgt_mean_anom), by = c("installation", "date")
    )

# write_rds(daily_nldas, file = "D:/data/daily_nldas.rds")

daily_nldas <- read_rds(file = "D:/data/daily_nldas.rds")
```

## Load case-control strata
Inspect Portsmouth NMC

```{r}

case_control_df <-
  read_rds("data/case_control_df.rds")



case_control_df %>% count(installation_name) %>% View()



# inspect Portsmouth DMISIDs (there is also a Navy Portsmouth shipyard in New Hampshire)

case_control_df %>% 
  filter(installation_name %in% "PORTSMOUTH") %>% 
  count(dmisid)


dmisid_distinct <-    
  read_rds(file = "data/dmisid_distinct.Rds")

dmisid_distinct %>% 
  filter(dmis_id %in% c("0124", "6317", "0321", "0380", "6322")
)

# DMISID's 0321 and 6322 are for New Hampshire, not Virginia (represent 20 encounters) 


case_control_df <-
  case_control_df %>% 
    mutate(installation_name = 
     recode(installation_name,
      "CAMP LEJEUNE" = "mcb_camp_lejeune",
      "CAMP PENDLETON" = "mcb_camp_pendleton",
      "EGLIN AFB" = "eglin_afb",
      "FT BENNING" = "fort_benning_ga",
      "FT BLISS" = "fort_bliss",
      "FT BRAGG" = "fort_bragg",
      "FT CAMPBELL" = "fort_campbell",
      "FT GORDON" = "fort_gordon",
      "FT HOOD" = "fort_hood",
      "FT IRWIN" = "ntc_and_fort_irwin",
      "FT JACKSON" = "fort_jackson",
      "FT KNOX" = "fort_knox",
      "FT LEONARD WOOD" = "fort_leonard_wood",
      "FT POLK" = "fort_polk",
      "FT RILEY" = "fort_riley",
      "FT SILL" = "fort_sill",
      "FT STEWART" = "fort_stewart",
      "JBSA" = "fort_sam_houston",
      "PARRIS ISLAND" = "mcrd_beaufort_parris_island",
      "PENSACOLA" = "pensacola",
      "PORTSMOUTH" = "portsmouth",
      "QUANTICO" = "mcb_quantico",
      "SAN DIEGO" = "mcrd_san_diego",
      "TWENTYNINE PALMS" = "twentynine_palms_main_base"
    )) %>% 
  filter(!dmisid %in% c("0321", "6322")) # Portsmouth shipyard, NH


#write_rds(case_control_df, file = "data/case_control_df.rds")




```

## Join case-crossover and daily exposures

```{r}

cc_exposure_df <-
  case_control_df %>% 
    left_join(daily_nldas,  by = c("installation_name" = "installation", "d_event" = "date")) %>% 
    filter(year %in% 1998:2019) %>% 
    mutate(stratum = as_factor(paste(studyid, d_event, sep = "_")))

#write_rds(cc_exposure_df, file = "D:/data/cc_exposure_df.rds")

cc_exposure_df <-
  read_rds(file = "D:/data/cc_exposure_df.rds")


# inspect: which cases are not matched? (all before 1998?)

cc_exposure_df %>% 
  count(installation_name) %>% View()


case_control_df %>% 
  count(installation_name) %>% View()


case_control_df[,1:4] %>% 
  anti_join(cc_exposure_df[,1:4])

# 8,336 encounters excluded (pre-1998 or post-2019)

# number excluded by year:

case_control_df[,1:4] %>% 
  anti_join(cc_exposure_df[,1:4]) %>% 
  count(lubridate::year(d_event))


```

## Conditional Logistic Model (no lag)

Inspect data, compare case days and control days
```{r}

cc_exposure_df %>% 
  count(case)
108233/31642 #3.42 cases per control


# Mean_WBGT

cc_exposure_df %>%
  group_by(installation_name, case) %>% 
  summarise(mean_wbgt = mean(Twbg_u_mean))


```

# CLM

- CLM all data
- CLM restrict winter months (DEC, JAN, FEB)


```{r}

# create strata column (studyid + d_event)

cc_exposure_df <-
  cc_exposure_df %>% 
    mutate(strata = as_factor(paste(studyid, d_event, sep = "_"))
)


cc_exposure_df %>% 
  group_by(strata) %>% 
  count(case)

clm_basic <- 
   survival::clogit(case ~ tmp_f_max95 +  
                   strata(strata), 
                   method = "efron", 
                   cc_exposure_df) 


summary(clm_basic)


# broom::tidy(clm_basic)
# broom::glance(clm_basic)

clm_augment <-
  broom::augment(clm_basic, cc_exposure_df)


clm_augment %>% 
  ggplot(aes(x = tmp_f_max95, y = .fitted)) + 
  geom_smooth(size = 1.5) + # method = 'gam' and formula 'y ~ s(x, bs = "cs")'
  geom_point(alpha = 0.05, size = 0.5) +
  theme_bw() +
    ylab("Odds of HSI")
  


# Remove winter months (Dec, Jan, Feb)

cc_exposure_mar_nov <-
  cc_exposure_df %>% 
    filter(!lubridate::month(d_event) %in% c(12, 01, 02))

```




# DLNM

## Lags function



```{r}

lags <- seq(7) # Number of lags

lag_names <- paste("lag", formatC(lags, width = nchar(max(lags)), flag = "0"), 
  sep = "_")

lag_fun <- setNames(paste("dplyr::lag(., ", lags, ")"), lag_names)

#  d %>% mutate_at(vars(x), funs_(lag_fun))

```



# Lag function for nested

```{r}

# for nested df by installation, with date in 1st column and index in 2nd 

create_lags_fun = function(df) {
  
  df %>% 
    mutate(lag_1 = dplyr::lag(dplyr::select(2), n = 1),
           lag_2 = dplyr::lag(dplyr::select(2), n = 2),
           lag_3 = dplyr::lag(dplyr::select(2), n = 3),
           lag_4 = dplyr::lag(dplyr::select(2), n = 4),
           lag_5 = dplyr::lag(dplyr::select(2), n = 5),
           lag_6 = dplyr::lag(dplyr::select(2), n = 6),
           lag_7 = dplyr::lag(dplyr::select(2), n = 7))
}

```





## Cross-basis

```{r}



selected_index <- "Twbg_u_mean"


# create lag matrix

lag_matrix <-
   daily_indices %>% 
    filter(date %in% as.Date("1997-12-15"):as.Date("2019-12-31")) %>% 
      dplyr::select(installation, date, selected_index) %>% 
   group_by(installation) %>% 
   mutate_at(vars(selected_index), funs_(lag_fun)
  )





# join lag matrix to case-crossover dataframe

cc_lag_matrix <-
  cc_exposure_df %>% 
    filter(year %in% 1998:2019) %>% 
    dplyr::select(!selected_index) %>%    # remove to avoid double listing after join
    left_join(lag_matrix,  by = c("installation_name" = "installation", "date" = "date")) 


cc_lag_only <- 
  cc_lag_matrix %>% 
  dplyr::select(selected_index, lag_1:lag_7)



# Define dlnm cross-basis (penalized splines)

index_cb <-
    crossbasis(
      cc_lag_only,    
      lag = 7,    # of lags
      argvar = list(fun = "ns", df = 5),    #  functional form of the dose-response curve
      arglag = list(fun = "ns", df = 4))    #  functional form of the lags

summary(index_cb)


# DEFINE THE PENALTY MATRICES
 # https://github.com/gasparrini/2017_gasparrini_Biomet_Rcodedata/blob/master/example1/ex1_01.ext.R

# cb_Pen <- cbPen(index_cb)


```

```{r}
# run model and get prediction for selected_index


#cc_exposure_df <-   cc_exposure_df %>% 
#  mutate(stratum = paste(studyid, d_event, sep = " "))


index_dlnm <- survival::clogit(case ~ 
                  index_cb +  # lagged, nonlinear term for exposure
                  strata(stratum), 
                  method = "efron",
                  data =  cc_exposure_df) 


pred_dlnm <- crosspred(index_cb, index_dlnm, cumul = TRUE)





```

Plot cross-predictions
```{r}

# 3d Plot 

plot(pred_dlnm, 
     xlab = paste(selected_index), zlab = "\nRR", ylab = "\nLag", 
     theta = 40, phi = 30, lphi = 30,
     main = "1998-2019")

crosspred_plot <-  
  plot(pred_dlnm, 
       xlab = paste(selected_index), zlab = "\nRR", ylab = "\nLag", 
       theta = 40, phi = 30, lphi = 30,
       main = "1998-2019")



# Slice Plot
# visualize association at specific lags 


# Plot dose-response curve at Lag 0

# par(mar = c(5.1, 4.1, 4.1, 2.1))


```


```{r}

plot(pred_dlnm, "slices",
     lag = 0,
     #ylim = c(0, 10),
     lwd = 4,
     col = "darkred",
     main = "Exposure-Response at Lag 0 \n  1998-2019", 
     xlab = paste(selected_index), 
     ylab = "HSI Rate Ratio")


plot(pred_dlnm, "slices",
     lag = 1,
     lwd = 4,
     col = "darkred",
     main = "Exposure-Response at Lag 1 \n  1998-2019", 
     xlab = paste(selected_index), 
     ylab = "HSI Rate Ratio")

plot(pred_dlnm, "slices",
     lag = 2,
     lwd = 4,
     col = "darkred",
     main = "Exposure-Response at Lag 2 \n  1998-2019", 
     xlab = paste(selected_index), 
     ylab = "HSI Rate Ratio")

plot(pred_dlnm, "slices",
     lag = 3,
     lwd = 4,
     col = "darkred",
     main = "Exposure-Response at Lag 3 \n  1998-2019", 
     xlab = paste(selected_index), 
     ylab = "HSI Rate Ratio")

plot(pred_dlnm, "slices",
     lag = 4,
     lwd = 4,
     col = "darkred",
     main = "Exposure-Response at Lag 4 \n  1998-2019", 
     xlab = paste(selected_index), 
     ylab = "HSI Rate Ratio")
```



```{r}
plot(pred_dlnm, "slices",
     var = 60,
     lwd = 4,
     col = "darkred",
     main = "Lag-Response at 60  \n  1998-2019", 
     xlab = "Days Lag", 
     ylab = "HSI Rate Ratio")

plot(pred_dlnm, "slices",
     var = 70,
     lwd = 4,
     col = "darkred",
     main = "Lag-Response at 70 \n  1998-2019", 
     xlab = "Days Lag", 
     ylab = "HSI Rate Ratio")


plot(pred_dlnm, "slices",
     var = 80,
     lwd = 4,
     col = "darkred",
     main = "Lag-Response at 80 \n  1998-2019", 
     xlab = "Days Lag", 
     ylab = "HSI Rate Ratio")

```







