---
title: "figures"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(plotly)
library(viridis)
library(ggrepel)
library(gridExtra)
library(patchwork)
```




## Single patchwork plot


```{r, eval = FALSE}

# Read in ggplot objects

plot_mean_temp <-
  read_rds("output/plot_tmp_f_mean.rds")

plot_max_temp <-
  read_rds("output/plot_tmp_f_max.rds")

plot_mean_hi <-
  read_rds("output/plot_heat_index_mean.rds")

plot_max_hi <-
  read_rds("output/plot_heat_index_max.rds")

plot_mean_wbgt <-
  read_rds("output/plot_wbgt_mean.rds")

plot_max_wbgt <-
  read_rds("output/plot_wbgt_max.rds")



plot_df_4_4 <-
  (plot_mean_temp | plot_mean_hi | plot_mean_wbgt) / 
  (plot_max_temp | plot_max_hi | plot_max_wbgt) + plot_layout(guides = "collect") + plot_annotation(tag_levels = 'A') & theme(legend.position = "bottom")


ggsave("output/plot_region_df_4_4.png")

plot_df_4_4

```


```{r}
# Read in ggplot objects

plot_mean_temp <-
  read_rds("output/plot_tmp_f_mean_lag_slice_cum.rds")

plot_max_temp <-
  read_rds("output/plot_tmp_f_max_lag_slice_cum.rds")

plot_mean_hi <-
  read_rds("output/plot_heat_index_mean_lag_slice_cum.rds")

plot_max_hi <-
  read_rds("output/plot_heat_index_max_lag_slice_cum.rds")

plot_mean_wbgt <-
  read_rds("output/plot_wbgt_mean_lag_slice_cum.rds")

plot_max_wbgt <-
  read_rds("output/plot_wbgt_max_lag_slice_cum.rds")



plot_df_4_4 <-
  (plot_mean_temp | plot_mean_hi | plot_mean_wbgt) / 
  (plot_max_temp | plot_max_hi | plot_max_wbgt) + plot_layout(guides = "collect") + plot_annotation(tag_levels = 'A') & theme(legend.position = "bottom")


ggsave("output/plot_region_df_4_4_lag_slice_cum.png")

plot_df_4_4
```

















## Patchwork plots for combined indices


```{r, message = FALSE}

selected_index <- c("tmp_f_mean", "heat_index_mean","wbgt_mean","tmp_f_max", "heat_index_max", "wbgt_max")

suffix <- c("", "_lag_slice", "_lag_slice_cum", "_region", "_service",
           "_tis", "_hsi", "_source", "_base")



patchwork_df_4_4 <-
  purrr::map(.x = suffix,
      ~(read_rds(paste0("output/plot_", selected_index[1], .x, ".rds")) |   
         read_rds(paste0("output/plot_", selected_index[2], .x, ".rds")) |  
         read_rds(paste0("output/plot_", selected_index[3], .x, ".rds"))   
         ) /
        (read_rds(paste0("output/plot_", selected_index[4], .x, ".rds")) |   
         read_rds(paste0("output/plot_", selected_index[5], .x, ".rds")) |  
         read_rds(paste0("output/plot_", selected_index[6], .x, ".rds"))) +
            plot_annotation(tag_levels = 'A') +
            plot_layout(guides = 'collect') & 
            theme(legend.position = "bottom")
  )


write_rds(patchwork_df_4_4, "output/patchwork_df_4_4.rds")     


patchwork_df_5_4 <-
  read_rds("output/patchwork_df_5_4.rds")

patchwork_df_4_4[3]

      

```




## OR Table

```{r}

selected_index <- c("tmp_f_mean", "heat_index_mean","wbgt_mean","tmp_f_max", "heat_index_max", "wbgt_max")


# read_rds("output/or_table_wbgt_max.rds")

or_df_4_4 <-
  purrr::map_df(.x = selected_index,
             ~bind_rows(read_rds(paste0("output/or_table_", .x, ".rds")))
  ) %>% 
  mutate(index_key = index,
         index = 
           case_when(
              index %in% "wbgt_mean" ~ "Mean WBGT (°F)",
              index %in% "wbgt_max" ~ "Max WBGT (°F)",
              index %in% "heat_index_mean" ~ "Mean Heat Index (°F)",
              index %in% "heat_index_max" ~ "Max Heat Index (°F)",
              index %in% "tmp_f_mean" ~ "Mean Temperature (°F)",
              index %in% "tmp_f_max" ~ "Max Temperature (°F)"),
          or_ci = paste0(format(round(rr, digits = 2), nsmall = 2, trim = "TRUE"), 
                         " (", format(round(ci_low, digits = 2), nsmall = 2, trim = "TRUE"), ", ",
                         format(round(ci_high, digits = 2), nsmall = 2, trim = "TRUE"), ")")
        ) %>% 
    rename(or = rr,
           value = var) 
  


or_df_4_4 



```


```{r}

# OR table (wide)
or_df_4_4 %>% 
  dplyr::select(-c(index_key, or, ci_low, ci_high)) %>% 
  filter(value %in% seq(from = 65, to = 115, by = 5)) %>%
  pivot_wider(names_from = value, values_from = or_ci) %>% 
  knitr::kable()

# OR table ("long"- transposed)

or_df_4_4 %>% 
  dplyr::select(-c(index_key, or, ci_low, ci_high)) %>% 
  #filter(value %in% seq(from = 65, to = 115, by = 5)) %>% 
  pivot_wider(names_from = index, values_from = or_ci) %>% 
  knitr::kable()

or_df_4_4_long <-
  or_df_4_4 %>% 
    dplyr::select(-c(index_key, or, ci_low, ci_high)) %>% 
    #filter(value %in% seq(from = 65, to = 115, by = 5)) %>% 
    pivot_wider(names_from = index, values_from = or_ci)


or_df_4_4_long %>% View()

write.csv(or_df_4_4_long, file = "output/or_df_4_4_long.csv")
```







## Initial plots
```{r, eval = FALSE}

# gridExtra
gridExtra::grid.arrange(plot_mean_temp, plot_mean_hi, plot_mean_wbgt, 
                        plot_max_temp, plot_max_hi, plot_max_wbgt, nrow = 2, ncol = 3)



# patchwork


(plot_mean_temp | plot_mean_hi | plot_mean_wbgt) / 
(plot_max_temp | plot_max_hi | plot_max_wbgt)


  # Tagging: https://patchwork.data-imaginist.com/articles/guides/annotation.html


plot_overall_df_5_4 <-
  (plot_mean_temp | plot_mean_hi | plot_mean_wbgt) / 
  (plot_max_temp | plot_max_hi | plot_max_wbgt) + plot_annotation(tag_levels = 'A')

# ggsave("output/plot_overall_df_5_4.png")

plot_overall_df_5_4


```




## Overall OR plots 
```{r, eval = FALSE}

# Read in ggplot objects

plot_mean_temp <-
  read_rds("output/plot_tmp_f_mean.rds")

plot_max_temp <-
  read_rds("output/plot_tmp_f_max.rds")

plot_mean_hi <-
  read_rds("output/plot_heat_index_mean.rds")

plot_max_hi <-
  read_rds("output/plot_heat_index_max.rds")

plot_mean_wbgt <-
  read_rds("output/plot_wbgt_mean.rds")

plot_max_wbgt <-
  read_rds("output/plot_wbgt_max.rds")



plot_df_5_4 <-
  (plot_mean_temp | plot_mean_hi | plot_mean_wbgt) / 
  (plot_max_temp | plot_max_hi | plot_max_wbgt) + plot_layout(guides = "collect") + plot_annotation(tag_levels = 'A') & theme(legend.position = "bottom")


ggsave("output/plot_region_df_5_4.png")

plot_region_df_5_4

```





## Overall OR plots by Region
```{r, eval = FALSE}

# Read in ggplot objects

plot_mean_temp_region <-
  read_rds("output/plot_mean_temp_region.rds")

plot_max_temp_region <-
  read_rds("output/plot_max_temp_region.rds")

plot_mean_hi_region <-
  read_rds("output/plot_mean_hi_region.rds")

plot_max_hi_region <-
  read_rds("output/plot_max_hi_region.rds")

plot_mean_wbgt_region <-
  read_rds("output/plot_mean_wbgt_region.rds")

plot_max_wbgt_region <-
  read_rds("output/plot_max_wbgt_region.rds")



plot_region_df_5_4 <-
  (plot_mean_temp_region | plot_mean_hi_region | plot_mean_wbgt_region) / 
  (plot_max_temp_region | plot_max_hi_region | plot_max_wbgt_region) + plot_layout(guides = "collect") + plot_annotation(tag_levels = 'A') & theme(legend.position = "bottom")


ggsave("output/plot_region_df_5_4.png")

plot_region_df_5_4

```


## Overall OR plots by Region
```{r, eval = FALSE}

# Read in ggplot objects

plot_mean_temp_region <-
  read_rds("output/plot_mean_temp_region.rds")

plot_max_temp_region <-
  read_rds("output/plot_max_temp_region.rds")

plot_mean_hi_region <-
  read_rds("output/plot_mean_hi_region.rds")

plot_max_hi_region <-
  read_rds("output/plot_max_hi_region.rds")

plot_mean_wbgt_region <-
  read_rds("output/plot_mean_wbgt_region.rds")

plot_max_wbgt_region <-
  read_rds("output/plot_max_wbgt_region.rds")



plot_region_df_5_4 <-
  (plot_mean_temp_region | plot_mean_hi_region | plot_mean_wbgt_region) / 
  (plot_max_temp_region | plot_max_hi_region | plot_max_wbgt_region) + plot_layout(guides = "collect") + plot_annotation(tag_levels = 'A') & theme(legend.position = "bottom")


ggsave("output/plot_region_df_5_4.png")
plot_region_df_5_4

```





## Overall OR plots by region
```{r, eval = FALSE}

# Read in ggplot objects

plot_tmp_f_mean_region <-
  read_rds("output/plot_tmp_f_mean_region.rds")

plot_tmp_f_max_region <-
  read_rds("output/plot_tmp_f_max_region.rds")

plot_heat_index_mean_region <-
  read_rds("output/plot_heat_index_mean_region.rds")

plot_heat_index_max_region <-
  read_rds("output/plot_heat_index_max_region.rds")

plot_wbgt_mean_region <-
  read_rds("output/plot_wbgt_mean_region.rds")

plot_wbgt_max_region <-
  read_rds("output/plot_wbgt_max_region.rds")



plot_region_df_5_4 <-
  (plot_tmp_f_mean_region | plot_heat_index_mean_region | plot_wbgt_mean_region) / 
  (plot_tmp_f_max_region | plot_heat_index_max_region | plot_wbgt_max_region) + plot_layout(guides = "collect") + plot_annotation(tag_levels = 'A') & theme(legend.position = "bottom")


ggsave("output/plot_region_df_5_4.png")
plot_region_df_5_4

```



