---
title: "master_function"
output: 
  html_document:
   keep_md: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(plotly)
library(lattice)
#remotes::install_github("tylermorganwall/rayshader")
library(rayshader)
library(dlnm)
library(survival)
library(splines)
library(broom)
library(weathermetrics)
library(viridis)
library(reshape2)
library(magick)
library(av)
library(ggrepel)


citation()
citation("dlnm")
citation("survival")
```

## Input data

```{r}

cc_exposure_df <-
  read_rds(file = "data/cc_exposure_df.rds") 

cc_exposure_df <-
  cc_exposure_df %>% 
    mutate("wbgt_mean" = weathermetrics::celsius.to.fahrenheit(wbgt_mean),
           "wbgt_max" = weathermetrics::celsius.to.fahrenheit(wbgt_max),
           source = tolower(source))


base_service_df <-
   read_rds(file = "data/base_service_df.rds") 

# Add installation branch of service and climate region

cc_exposure_df <-
  cc_exposure_df %>% 
    left_join(base_service_df %>%
                rename(base_service = service) %>% 
                dplyr::select(installation_name, base_service, region), by = "installation_name") 



daily_indices <- 
  read_rds(file = "data/daily_indices.rds") %>% 
    filter(!installation %in% c("fort_drum", "fort_huachuca", "fort_lewis",
                                "lackland_afb", "fort_carson", "west_point_mil_reservation")) %>% 
    mutate("wbgt_mean" = weathermetrics::celsius.to.fahrenheit(wbgt_mean),
           "wbgt_max" = weathermetrics::celsius.to.fahrenheit(wbgt_max),
            installation = recode(installation,
              "mcb_camp_lejeune" = "camp_lejeune",
              "mcb_camp_pendleton" = "camp_pendleton",
              "fort_benning_ga" = "fort_benning",
              "fort_sam_houston" = "jbsa",
              "mcrd_beaufort_parris_island" = "parris_island",
              "mcb_quantico" = "quantico",
              "twentynine_palms_main_base" = "twentynine_palms")) 
     
```



## Inputs

```{r}

# selected_index <- "tmp_f_max"

selected_index <- c("tmp_f_mean", "heat_index_mean","wbgt_mean","tmp_f_max", "heat_index_max", "wbgt_max")

# crossbasis options
set_lag <- 5    # total number days lag to assess
set_dr_df <- 4   # natural spline degrees of freedom for functional form of the dose-response curve
set_lag_df <- 4   # natural spline degrees of freedom for functional form of the lag

# crosspred options

set_increment <- 1   # crosspred "by = "
# set_centered <- median(eval(parse(text = paste0("cc_exposure_df$", selected_index))))       #60     # crosspred "cen= ", centered value for odds ratios 
set_min_temp <- 32   # crosspred lower bound


# crosspred upper-bound: move into function
# set_max_temp <- case_when(
#   selected_index %in% "wbgt_mean" ~ 90,
#   selected_index %in% "wbgt_max" ~ 110,
#   selected_index %in% "heat_index_mean" ~ 110,
#   selected_index %in% "heat_index_max" ~ 120,
#   selected_index %in% "tmp_f_mean" ~ 105,
#   selected_index %in% "tmp_f_max" ~ 120,
#     )
# 
# set_max_temp


# # set max plot index value (approximate, or rounded-down from max value in dataset)
# set_max_plot_value <- case_when(
#   selected_index %in% "wbgt_mean" ~ 86,
#   selected_index %in% "wbgt_max" ~ 104,
#   selected_index %in% "heat_index_mean" ~ 104,
#   selected_index %in% "heat_index_max" ~ 116,
#   selected_index %in% "tmp_f_mean" ~ 98,
#   selected_index %in% "tmp_f_max" ~ 112,
#     )
# 
# set_max_plot_value
# 
# 
# print_index <- case_when(
#   selected_index %in% "wbgt_mean" ~ "Mean WBGT (°F)",
#   selected_index %in% "wbgt_max" ~ "Max WBGT (°F)",
#   selected_index %in% "heat_index_mean" ~ "Mean Heat Index (°F)",
#   selected_index %in% "heat_index_max" ~ "Max Heat Index (°F)",
#   selected_index %in% "tmp_f_mean" ~ "Mean Temperature (°F)",
#   selected_index %in% "tmp_f_max" ~ "Max Temperature (°F)",
#     )
# 
# 
# print_index



```


## Lag function
```{r}

# DLNM
## Lags function

lags <- seq(set_lag) # Number of lags

lag_names <- paste("lag", formatC(lags, width = nchar(max(lags)), flag = "0"), 
  sep = "_")

lag_fun <- setNames(paste("dplyr::lag(., ", lags, ")"), lag_names)

```



## Create lag matrix for selected index; join to case-crossover dataframe

```{r, warning = FALSE}
 # create lag matrix


cc_dlnm_fun <-  function(selected_index) {

lag_matrix <-
  daily_indices %>% 
    filter(date %in% as.Date("1997-12-15"):as.Date("2019-12-31")) %>% 
      dplyr::select(installation, date, selected_index) %>% 
   group_by(installation) %>% 
   mutate_at(vars(selected_index), funs_(lag_fun)
  )


# join lag matrix to case-crossover dataframe

cc_lag_matrix <-
  cc_exposure_df %>% 
    filter(year %in% 1998:2019) %>% 
    dplyr::select(!selected_index) %>%    # remove to avoid double listing after join
    left_join(lag_matrix,  by = c("installation_name" = "installation", "date" = "date")) 


cc_lag_only <- 
  cc_lag_matrix %>% 
  dplyr::select(selected_index, lag_1:paste0("lag_", set_lag))

## Define DLNM cross-basis

 
# Define dlnm cross-basis (penalized splines)

index_cb <-
    crossbasis(
      cc_lag_only,    
      lag = set_lag,    # of lags
      argvar = list(fun = "ns", df = set_dr_df),    #  functional form of the dose-response curve
      arglag = list(fun = "ns", df = set_lag_df))    #  functional form of the lags

summary(index_cb)

# run model and get prediction for selected_index


index_dlnm <- survival::clogit(case ~ 
                  index_cb +  # lagged, nonlinear term for exposure
                  strata(stratum), 
                  method = "exact",
                  data =  cc_exposure_df) 



# centered value from index median

set_centered <- median(eval(parse(text = paste0("cc_exposure_df$", selected_index))))  

# max_temp based on selected index

set_max_temp <- case_when(
  selected_index %in% "wbgt_mean" ~ 90,
  selected_index %in% "wbgt_max" ~ 110,
  selected_index %in% "heat_index_mean" ~ 110,
  selected_index %in% "heat_index_max" ~ 120,
  selected_index %in% "tmp_f_mean" ~ 105,
  selected_index %in% "tmp_f_max" ~ 120,
    )


# set max plot index value (approximate, or rounded-down from max value in dataset)
set_max_plot_value <- case_when(
  selected_index %in% "wbgt_mean" ~ 86,
  selected_index %in% "wbgt_max" ~ 104,
  selected_index %in% "heat_index_mean" ~ 104,
  selected_index %in% "heat_index_max" ~ 116,
  selected_index %in% "tmp_f_mean" ~ 98,
  selected_index %in% "tmp_f_max" ~ 112,
    )



print_index <- case_when(
  selected_index %in% "wbgt_mean" ~ "Mean WBGT (°F)",
  selected_index %in% "wbgt_max" ~ "Max WBGT (°F)",
  selected_index %in% "heat_index_mean" ~ "Mean Heat Index (°F)",
  selected_index %in% "heat_index_max" ~ "Max Heat Index (°F)",
  selected_index %in% "tmp_f_mean" ~ "Mean Temperature (°F)",
  selected_index %in% "tmp_f_max" ~ "Max Temperature (°F)",
    )


# DLNM cross-prediction

pred_dlnm <- crosspred(index_cb, index_dlnm, by = set_increment, from = set_min_temp, to = set_max_temp, cen = set_centered, cumul = TRUE)


summary(pred_dlnm)


## Odds ratio table 
#(Relative to centered value)



# full range
  # allRRfit: vector of exponentiated overall cumulative associations from allfit.


assign(paste0("or_table_", selected_index),
  bind_cols(names(pred_dlnm$allRRfit), pred_dlnm$allRRfit, pred_dlnm$allRRlow, pred_dlnm$allRRhigh) %>% 
    dplyr::rename(var = 1, rr = 2, ci_low = 3, ci_high = 4) %>% 
    mutate(index = selected_index)
)


write_rds(eval(parse(text = paste0("or_table_", selected_index))), 
  file = paste0("output/", paste0("or_table_", selected_index), ".rds"))


eval(parse(text = paste0("or_table_", selected_index))) %>% 
  knitr::kable()


## Plot model (ggplot)

# As ggplot
  # https://www.rdocumentation.org/packages/season/versions/0.3.8/vignettes/season-vignette.Rmd link assisted with example "Plot of the temperature and death association averaging over all lags"

   # allRRfit: vector of exponentiated overall cumulative associations from allfit.
 
to_plot <- 
  data.frame(index = pred_dlnm$predvar, 
             mean = pred_dlnm$allRRfit,
             lower = pred_dlnm$allRRlow,
             upper = pred_dlnm$allRRhigh) %>% 
  filter(index <= set_max_plot_value)
  


assign(paste0("plot_", selected_index),
  ggplot(data = to_plot, aes(x = index, y = mean, ymin = lower, ymax = upper)) +
    geom_hline(lty = 2, yintercept = 1) + # horizontal reference line at no change in odds
    geom_ribbon(alpha = 0.4, fill = "cadetblue", color = "cadetblue") +
    geom_line(size = 2) +
    # geom_point(aes(x = set_centered, y = 1), size = 2.5) +
    # geom_text(aes(x = set_centered, y = 1, label = format(round(set_centered, digits = 1), nsmall = 1)),
    #           nudge_x = -2,
    #           nudge_y = 0.25,
    #           size = 4) +
    xlab(print_index) +
    ylab('Odds Ratio') +
    labs(caption = paste0("ORs relative to ",  print_index, " = ", set_centered)) +
    #labs(subtitle = paste0("Centered at ", format(round(set_centered, digits = 1), nsmall = 1))) +
    coord_cartesian(xlim = c(NA, set_max_plot_value)) +
    theme_bw() 
  )
    

write_rds(eval(parse(text = paste0("plot_", selected_index))), 
  file = paste0("output/", paste0("plot_", selected_index), ".rds"))


eval(parse(text = paste0("plot_", selected_index))) +
    ggtitle(paste0("Daily ", print_index, " and HSI association cumulative over 0-",
                   set_lag, " days lag")) +
    labs(caption = paste0("ORs relative to ",  print_index, " = ", set_centered)) +
    theme(plot.caption = element_text(hjust = 0))

}

```


```{r}

purrr::map(selected_index, cc_dlnm_fun) 

purrr::map(selected_index, cc_dlnm_fun_lag) 

```

## Lag Plots

```{r}

cc_dlnm_fun_lag <-  function(selected_index) {

lag_matrix <-
  daily_indices %>% 
    filter(date %in% as.Date("1997-12-15"):as.Date("2019-12-31")) %>% 
      dplyr::select(installation, date, selected_index) %>% 
   group_by(installation) %>% 
   mutate_at(vars(selected_index), funs_(lag_fun)
  )


# join lag matrix to case-crossover dataframe

cc_lag_matrix <-
  cc_exposure_df %>% 
    filter(year %in% 1998:2019) %>% 
    dplyr::select(!selected_index) %>%    # remove to avoid double listing after join
    left_join(lag_matrix,  by = c("installation_name" = "installation", "date" = "date")) 


cc_lag_only <- 
  cc_lag_matrix %>% 
  dplyr::select(selected_index, lag_1:paste0("lag_", set_lag))

## Define DLNM cross-basis

 
# Define dlnm cross-basis (penalized splines)

index_cb <-
    crossbasis(
      cc_lag_only,    
      lag = set_lag,    # of lags
      argvar = list(fun = "ns", df = set_dr_df),    #  functional form of the dose-response curve
      arglag = list(fun = "ns", df = set_lag_df))    #  functional form of the lags

summary(index_cb)

# run model and get prediction for selected_index


index_dlnm <- survival::clogit(case ~ 
                  index_cb +  # lagged, nonlinear term for exposure
                  strata(stratum), 
                  method = "exact",
                  data =  cc_exposure_df) 



# centered value from index median

set_centered <- median(eval(parse(text = paste0("cc_exposure_df$", selected_index))))  

# max_temp based on selected index

set_max_temp <- case_when(
  selected_index %in% "wbgt_mean" ~ 90,
  selected_index %in% "wbgt_max" ~ 110,
  selected_index %in% "heat_index_mean" ~ 110,
  selected_index %in% "heat_index_max" ~ 120,
  selected_index %in% "tmp_f_mean" ~ 105,
  selected_index %in% "tmp_f_max" ~ 120,
    )


# set max plot index value (approximate, or rounded-down from max value in dataset)
set_max_plot_value <- case_when(
  selected_index %in% "wbgt_mean" ~ 86,
  selected_index %in% "wbgt_max" ~ 104,
  selected_index %in% "heat_index_mean" ~ 104,
  selected_index %in% "heat_index_max" ~ 116,
  selected_index %in% "tmp_f_mean" ~ 98,
  selected_index %in% "tmp_f_max" ~ 112,
    )



print_index <- case_when(
  selected_index %in% "wbgt_mean" ~ "Mean WBGT (°F)",
  selected_index %in% "wbgt_max" ~ "Max WBGT (°F)",
  selected_index %in% "heat_index_mean" ~ "Mean Heat Index (°F)",
  selected_index %in% "heat_index_max" ~ "Max Heat Index (°F)",
  selected_index %in% "tmp_f_mean" ~ "Mean Temperature (°F)",
  selected_index %in% "tmp_f_max" ~ "Max Temperature (°F)",
    )


# DLNM cross-prediction

pred_dlnm <- crosspred(index_cb, index_dlnm, by = set_increment, from = set_min_temp, to = set_max_temp, cen = set_centered, cumul = TRUE)


summary(pred_dlnm)





# Slice by lag
    # matRRfit: matrix of exponentiated specific associations from matfit
    # matfit: matrices of predictions and standard errors at the chosen combinations of predictor and lag values


to_plot_slice <- 
  pred_dlnm$matRRfit %>% 
    as.data.frame() %>% 
    rownames_to_column() %>% 
    rename(index_value = rowname) %>% 
    as_tibble() %>% 
    pivot_longer(-index_value, names_to = "lag", values_to = "OR") %>% 
  bind_cols(

    pred_dlnm$matRRlow %>% 
        as.data.frame() %>% 
        rownames_to_column() %>% 
        rename(index_value = rowname) %>% 
        as_tibble() %>% 
        pivot_longer(-index_value, names_to = "lag", values_to = "OR_low") %>% 
      dplyr::select(OR_low)
  ) %>% 
  bind_cols(
    
    pred_dlnm$matRRhigh %>% 
        as.data.frame() %>% 
        rownames_to_column() %>% 
        rename(index_value = rowname) %>% 
        as_tibble() %>% 
        pivot_longer(-index_value, names_to = "lag", values_to = "OR_high") %>% 
      dplyr::select(OR_high)
) %>% 
   mutate(index_value = as.numeric(index_value))







assign(paste0("plot_", selected_index, "_lag_slice"),
  ggplot(data = to_plot_slice, aes(x = index_value, color = lag)) +
    geom_hline(lty = 2, yintercept = 1) + # horizontal reference line at no change in odds
    geom_line(aes(y = OR), se = FALSE, size = 1.2) +
    geom_line(aes(y = OR_low), se = FALSE, size = 0.3, linetype = "dotted") +
    geom_line(aes(y = OR_high), se = FALSE, size = 0.3, linetype = "dotted") +
    xlab(print_index) +
    ylab('Odds Ratio') +
    labs(caption = paste0("ORs relative to ",  print_index, " = ", set_centered)) +
    #labs(caption = paste0("Centered at ", format(round(set_centered, digits = 1), nsmall = 1))) +
    coord_cartesian(xlim = c(NA, set_max_plot_value)) +
    theme(legend.position = "bottom") +
    theme_bw() 
)
  
  
write_rds(eval(parse(text = paste0("plot_", selected_index, "_lag_slice"))), 
  file = paste0("output/", paste0("plot_", selected_index, "_lag_slice"), ".rds"))


eval(parse(text = paste0("plot_", selected_index, "_lag_slice"))) 



# Cumulative by lag  
  
    # cumRRfit: matrix of exponentiated incremental cumulative associations from cumfit
    # cumfit: matrices of incremental cumulative predicted associations along lags and related standard errors at the chosen combinations of predictor and (integer) lag values
  
  
to_plot_slice_cum <- 
  pred_dlnm$cumRRfit %>% 
    as.data.frame() %>% 
    rownames_to_column() %>% 
    rename(index_value = rowname) %>% 
    as_tibble() %>% 
    pivot_longer(-index_value, names_to = "lag", values_to = "OR") %>% 
  bind_cols(

    pred_dlnm$cumRRlow %>% 
        as.data.frame() %>% 
        rownames_to_column() %>% 
        rename(index_value = rowname) %>% 
        as_tibble() %>% 
        pivot_longer(-index_value, names_to = "lag", values_to = "OR_low") %>% 
      dplyr::select(OR_low)
  ) %>% 
  bind_cols(
    
    pred_dlnm$cumRRhigh %>% 
        as.data.frame() %>% 
        rownames_to_column() %>% 
        rename(index_value = rowname) %>% 
        as_tibble() %>% 
        pivot_longer(-index_value, names_to = "lag", values_to = "OR_high") %>% 
      dplyr::select(OR_high)
) %>% 
  mutate(index_value = as.numeric(index_value))


to_plot_slice_cum

assign(paste0("plot_", selected_index, "_lag_slice_cum"),
  ggplot(data = to_plot_slice_cum, aes(x = index_value, color = lag)) +
    geom_hline(lty = 2, yintercept = 1) + # horizontal reference line at no change in odds
    geom_line(aes(y = OR), se = FALSE, size = 1.2) +
    geom_line(aes(y = OR_low), se = FALSE, size = 0.3, linetype = "dotted") +
    geom_line(aes(y = OR_high), se = FALSE, size = 0.3, linetype = "dotted") +
    xlab(print_index) +
    ylab('Odds Ratio') +
    labs(caption = paste0("ORs relative to ",  print_index, " = ", set_centered)) +
    #labs(subtitle = paste0("Centered at ", format(round(set_centered, digits = 1), nsmall = 1))) +
    coord_cartesian(xlim = c(NA, set_max_plot_value)) +
    theme_bw() 
)



write_rds(eval(parse(text = paste0("plot_", selected_index, "_lag_slice_cum"))), 
  file = paste0("output/", paste0("plot_", selected_index, "_lag_slice_cum"), ".rds"))


paste0("plot_", selected_index, "_lag_slice_cum")

eval(parse(text = paste0("plot_", selected_index, "_lag_slice_cum"))) 

}
```

```{r}
plot_tmp_f_max_base
```

