---
title: "met_summary"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


library(tidyverse)
library(lubridate)
library(forcats)

```


Load hourly index dataframe 

```{r}

hourly_nldas <-
  read_rds(file = "D:/data/hourly_nldas.rds")

hourly_nldas %>% 
  summary(status)

```




# Daily/Monthly/Annual indices

```{r}

daily_indices <-
  hourly_nldas  %>%
    drop_na %>%
    dplyr::select(installation, local_dttm, tmp_f, heat_index, wbgt_u) %>% 
    group_by(installation, lubridate::date(local_dttm)) %>%
    dplyr::summarise_at(
          .vars = vars(tmp_f, heat_index, wbgt_u),
          .funs = c(mean = "mean", max = "max", min = "min", "max95" = ~quantile(., probs = 0.95)))

#write_rds(daily_indices, file = "D:/data/daily_indices.rds")


month_yr_indices <-
  hourly_nldas %>%
    drop_na %>%
    dplyr::select(installation, local_dttm, tmp_f, heat_index, wbgt_u) %>% 
    group_by(installation, lubridate::month(local_dttm), lubridate::year(local_dttm)) %>%
    dplyr::summarise_at(
          .vars = vars(tmp_f, heat_index, wbgt_u),
          .funs = c(mean = "mean", max = "max", "max99" = ~quantile(., probs = 0.99)))

#write_rds(month_yr_indices, file = "D:/data/month_yr_indices.rds")


monthly_indices <-
  hourly_nldas %>%
    drop_na %>%
    dplyr::select(installation, local_dttm, tmp_f, heat_index,wbgt_u) %>% 
    group_by(installation, lubridate::month(local_dttm)) %>%
    dplyr::summarise_at(
          .vars = vars(tmp_f, heat_index, wbgt_u),
          .funs = c(mean = "mean", max = "max", "max99" = ~quantile(., probs = 0.99))) 


annual_indices <-
   hourly_nldas %>%
    drop_na %>%
    dplyr::select(installation, local_dttm, tmp_f, heat_index, wbgt_u) %>% 
    group_by(installation, lubridate::year(local_dttm)) %>%
    dplyr::summarise_at(
          .vars = vars(tmp_f, heat_index, wbgt_u),
          .funs = c(mean = "mean", max = "max", "max99_5" = ~quantile(., probs = 0.995))) 

#write_rds(annual_indices, file = "D:/data/annual_indices.rds")
```


# Anomalies
https://sal2222.github.io/heat_stress/climatology.html



```{r}

#month-day for climatologies

month_day_indices <-
  hourly_nldas %>%
    drop_na %>%
    dplyr::select(installation, local_dttm, tmp_f, heat_index, wbgt_u) %>% 
    group_by(installation, lubridate::month(local_dttm), lubridate::day(local_dttm)) %>%
    dplyr::summarise_at(
          .vars = vars(tmp_f, heat_index, wbgt_u),
          .funs = (mean = "mean")) %>% 
  dplyr::rename(month = `lubridate::month(local_dttm)`,
                day = `lubridate::day(local_dttm)`)



daily_anomalies <-
  daily_indices %>%
    dplyr::select(installation, date = `lubridate::date(local_dttm)`, 
  tmp_f_mean, heat_index_mean, wbgt_u_mean) %>%
    mutate(month = lubridate::month(date),
         day = lubridate::day(date)) %>% 
    left_join(., month_day_indices, 
              by = c("installation", "month", "day") 
) %>% 
  mutate(tmp_mean_anom = tmp_f_mean - tmp_f,
         hi_mean_anom = heat_index_mean - heat_index,
         wbgt_mean_anom = wbgt_u_mean - wbgt_u)

# write_rds(daily_anomalies, file = "D:/data/daily_anomalies.rds")


```


```{r}

annual_indices %>%
  rename(year = `lubridate::year(local_dttm)`) %>% 
  filter(year > 1989 & year < 2019) %>% 
  ggplot(aes(x = year, y = Twbg_u_mean, color = installation)) +
  geom_point() +
  geom_smooth()


annual_indices %>%
  rename(year = `lubridate::year(local_dttm)`) %>% 
  filter(year > 1989 & year < 2019) %>% 
  ggplot(aes(x = year, y = Tnwb_u_max99_5, color = installation)) +
  geom_point() +
  geom_smooth()




annual_indices %>%
  rename(year = `lubridate::year(local_dttm)`) %>% 
  filter(year > 1989 & year < 2019) %>% 
  ggplot(aes(x = fct_reorder(installation, Tnwb_u_max99_5, .fun = median, .desc = TRUE), y = Tnwb_u_max99_5)) +
  geom_boxplot() +
    theme_bw() +
    theme(axis.text.x = element_text(angle = 90))



annual_indices %>%
  rename(year = `lubridate::year(local_dttm)`) %>% 
  filter(year > 1989 & year < 2019) %>% 
  ggplot(aes(x = fct_reorder(installation, Tnwb_u_max, .fun = median, .desc = TRUE), y = Tnwb_u_max)) +
  geom_boxplot() +
    theme_bw() +
    theme(axis.text.x = element_text(angle = 90))



annual_indices %>% 
  rename(year = `lubridate::year(local_dttm)`) %>% 
  filter(year %in% 2019) %>% View()
  

```

