---
title: "strata"
author: "SL"
date: "6/12/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(purrr)
library(forecast)
library(dlnm)
library(remotes)
library(case.crossover)
#remotes::install_github("RyanGan/case.crossover")
library(lubridate)

memory.limit()

# increase memory storage capacity
memory.limit(size = 56000)
   
```


## Case-crossover strata

```{r create_strata, eval = FALSE}

encounters_nest <-
  read_rds("data/encounters_nest.rds") 
    

encounters_nest %>% 
  unnest(data)
    



# Bragg strata

bragg_strata <-
  encounters_top10 %>% 
    dplyr::slice(1) %>% 
    unnest(data) %>%
    dplyr::mutate(id = paste(studyid, d_event, sep = "_") ) %>% 
    case.crossover::casecross(data = ., id = "id" , date = "d_event", covariate = F, period = "month") %>% 
  as_tibble() 

write_rds(bragg_strata, "data/bragg_strata.rds")


  

```


```{r}

### Create strata for case-crossover
# Identify  control days for each case day and assign exposures for each day  

# https://rdrr.io/github/RyanGan/case.crossover/man/casecross.html


# casecross(data, id, date, covariate = F, period = "month")
# Function creates a time-stratified case-crossover dataframe from a case-only dataframe 
# where the outcome on a particular date can be compared to referent periods on the same day of the week.
# 



casecross <- function(data, id, date, covariate=F, period = "month"){
  # if id value is given
  if (is.character(id)) {
    # vector of ids
    id_vec <- data[,id]
  } else {# else if no value provided, create an id variable
    id_vec <- seq(1, nrow(data), by = 1)
  }
  # vector of admit dates joined to the id vector
  event_date <- data[,date]
  id_date <- data.frame(id_vec, event_date)

  # find ref dates
  date_list <- apply(id_date, 1, function(x) {
    # output event date
    event_date <- as.Date(x[2])
    # day of week
    day_week <- wday(event_date)
    # create sequence of dates based on ref period
    date_seq <- seq.Date(floor_date(event_date, unit = period),
                         ceiling_date(event_date, unit = period), "days")
    # find dates on the same day of event date
    ref_dates <- as.character(date_seq[wday(date_seq) == day_week])

    # identifier
    identifier <- rep(x[1], length(ref_dates))
    # outcome
    outcome <- ifelse(as.Date(ref_dates) == x[2],1,0)
    id_date_vec <- cbind(identifier, ref_dates, outcome)
  })
  # bind lists together
  strat_data <- do.call(rbind, date_list)
  # remove row names
  rownames(strat_data) <- NULL
  colnames(strat_data) <- c("id", date, "outcome")
  # convert to dataframe
  strat_data <- data.frame(strat_data)
  # if covariates provided, join to the dataframe
  if (is.character(covariate)) {
    cov_data <- as.data.frame(cbind(id_vec, data[,covariate]))
    # names of cov data
    colnames(cov_data) <- c("id", covariate)
    # conver identifier to character to merge
    cov_data$id <- as.character(cov_data$id)
    # merge with ts_data
    strat_data <- merge(strat_data, cov_data, by = "id")
  }
  # return dataframe
  return(strat_data)
} # end function

```


```{r}

```






```{r}
bragg_strata <- 
  read_rds("data/bragg_strata.rds")

bragg_strata %>%
  dplyr::mutate(d_event = as.Date(d_event)) 
```

